apiVersion: apps/v1 # API that define deployments
kind: Deployment # Resource Type
metadata:
  name: first-deployment
  namespace: my-library-cluster-namespace #kubectl create namespace my-library-cluster-namespace
spec:
  replicas: 1 # Pod number
  selector: # How to find the pods that this deployment manage
    matchLabels:
      app: my-library # Connect Deployment to the Pods
  template: # Template Pods
    metadata:
      labels:
        app: my-library
    spec: # Containers definition
      containers:
      - name: rails-app
        image: mfdutra/mylibrary-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "development"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DATABASE_URL
          value: "postgres://rails:$(DB_PASSWORD)@postgres-service:5432/mylibrary_development"
        - name: CLOUDINARY_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUDINARY_URL
