name: "CI/CD - Ruby on Rails to Docker Hub"

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  # 1. TESTES E QUALIDADE (CI)
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine # Usei uma versão mais recente
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Faz cache automático das gems (mais rápido)

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rails test

  # 2. SEGURANÇA E ESTILO (LINT)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Security audit dependencies
        run: bundle exec bundle-audit check --update --ignore CVE-2025-55193 GHSA-r4mg-4433-c7g3 GHSA-wx95-c6cv-8532

      - name: Security audit application code
        run: bundle exec brakeman -q -w2 --except CheckEOLRuby,CheckEOLRails

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  # 3. CONSTRUÇÃO E ENVIO (CD)
  build-and-push-image:
    runs-on: ubuntu-latest
    # ESTA LINHA É A CHAVE: Só corre se o Test e o Lint passarem!
    needs: [test, lint]
    # Só faz o push se for merge na master (não em Pull Requests)
    if: github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mfdutra/mylibrary-web
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
